/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 *
 *   Created: Sun Aug 19 14:28:19 2001
 */
#ifndef __CEXTRACT__
#if __STDC__

extern h_t *h_open (int size, h_HashFunct hf, h_Comparator hc);
extern void h_close (h_t * ht);
extern int h_count (h_t * ht);
extern int h_insert (h_t * ht, void *ptr);
extern void *h_search (h_t * ht, void *key, void **ptr);
extern void *h_delete (h_t * ht, void *key, void **ptr);
extern int h_gather_data (h_t * ht, int *ac, void ***ptr);

#else /* __STDC__ */

extern h_t *h_open ( /* int size, h_HashFunct hf, h_Comparator hc */ );
extern void h_close ( /* h_t * ht */ );
extern int h_count ( /* h_t * ht */ );
extern int h_insert ( /* h_t * ht, void *ptr */ );
extern void *h_search ( /* h_t * ht, void *key, void **ptr */ );
extern void *h_delete ( /* h_t * ht, void *key, void **ptr */ );
extern int h_gather_data ( /* h_t * ht, int *ac, void ***ptr */ );

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
