/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 *
 *   Created: Tue Aug 21 11:08:41 2001
 */
#ifndef __CEXTRACT__
#if __STDC__

extern void mpiPi_getenv (void);
extern void mpiPi_copy_args (int *ac, char **av, int av_len);
extern void mpiPi_copy_given_args (int *ac, char **av, int av_len,
                                   int argc, char **argv);
extern void mpiPi_init (char *appName);
extern int callsite_pc_cache_comparator (const void *p1, const void *p2);
extern int callsite_pc_cache_hashkey (const void *p1);
extern int mpiPi_query_pc (void *pc, char **filename, char **functname,
			   int *lineno);
extern int callsite_src_id_cache_comparator (const void *p1, const void *p2);
extern int callsite_src_id_cache_hashkey (const void *p1);
extern int mpiPi_query_src (callsite_stats_t * p);
extern int mpiPi_mergeResults (void);
extern void mpiPi_publishResults (void);
extern void mpiPi_collect_basics (void);
extern void mpiPi_finalize (void);
extern void mpiPi_update_callsite_stats (unsigned op, unsigned rank,
					 void **pc, double dur,
					 double sendSize);
extern int find_src_loc (void *i_addr_hex, char **o_file_str, int *o_lineno,
			 char **o_funct_str);
extern int open_bfd_executable (char *filename);
extern int close_bfd_executable (void);
extern int mpiPi_profile_print (FILE * fp);
extern char *GetBaseAppName (char *rawName);
extern void mpiPi_RecordTraceBack (jmp_buf jb, void *pc_array[],
				   int max_back);

#else /* __STDC__ */

extern void mpiPi_getenv ( /* void */ );
extern void mpiPi_copy_args ( /* int *ac, char **av, int av_len */ );
extern void mpiPi_copy_given_args ();
extern void mpiPi_init ( /* char *appName */ );
extern int callsite_pc_cache_comparator (	/* const void *p1, const void *p2 */
  );
extern int callsite_pc_cache_hashkey ( /* const void *p1 */ );
extern int mpiPi_query_pc (
			    /* void *pc, char **filename, char **functname, int *lineno */
  );
extern int callsite_src_id_cache_comparator (
					      /* const void *p1, const void *p2 */
  );
extern int callsite_src_id_cache_hashkey ( /* const void *p1 */ );
extern int mpiPi_query_src ( /* callsite_stats_t * p */ );
extern int mpiPi_mergeResults ( /* void */ );
extern void mpiPi_publishResults ( /* void */ );
extern void mpiPi_collect_basics ( /* void */ );
extern void mpiPi_finalize ( /* void */ );
extern void mpiPi_update_callsite_stats (
					  /* unsigned op, unsigned rank, void **pc, double dur, double sendSize */
  );
extern int find_src_loc (
			  /* void *i_addr_hex, char **o_file_str, int *o_lineno, char **o_funct_str */
  );
extern int open_bfd_executable ( /* char *filename */ );
extern int close_bfd_executable ( /* void */ );
extern int mpiPi_profile_print ( /* FILE * fp */ );
extern char *GetBaseAppName ( /* char *rawName */ );
extern void mpiPi_RecordTraceBack (
				    /* jmp_buf jb, void *pc_array[], int max_back */
  );

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
